[BOSK-17] feat: Added MultiGrainedScanning block. Added small fix
NTAILab/bosk pull request #12
Opened 2022-10-22 16:00 UTC by AndreyAgeev

Added MultiGrainedScanning block

2022-10-25 07:46 UTC, andruekonst requested changes

2022-10-25 07:46 UTC, andruekonst commented on bosk/block/zoo/multi_grained_scanning/multi_grained_scanning.py
> +        self._models: List[Tuple[Any, Any]] = [(RandomForestClassifier(random_state), ExtraTreesClassifier(random_state))
It is better to pass classifier instances as an `__init__` input, instead of hard coding `RandomForestClassifier` and `ExtraTreesClassifier`.

2022-10-25 07:46 UTC, andruekonst commented on bosk/block/zoo/multi_grained_scanning/multi_grained_scanning.py
> +        self._windows: List[int] = windows
Is the support of multiple windows at a time necessary?
`MultiGrainedScanningBlock` can be instantiated several times with different window size to mimic the same behavior. But in that case, for example, it would allow for an executor to parallelize computations over window size.

**Suggestion:**
Use only one window size per `MultiGrainedScanningBlock`.

2022-10-25 07:46 UTC, andruekonst commented on bosk/block/zoo/multi_grained_scanning/multi_grained_scanning.py
> +    def _window_slicing_img(self, X, y, window, shape, stride=1):
2D multi-grained scanning could be implemented with the use of inheritance in, for example, `MultiGrainedScanning2DBlock`, by overriding `_window_slicing` method.
_This kind of interface is widely used in deep learning frameworks: `Conv2d` in Pytorch, `Conv2D` in Keras._

2022-10-25 07:46 UTC, andruekonst commented on bosk/block/zoo/multi_grained_scanning/multi_grained_scanning.py
> +        prf.fit(sliced_X, sliced_y)
These two lines can be joined into one loop over estimators.

2022-10-25 07:46 UTC, andruekonst commented on examples/deep_forests/mg_scanning/mg_scanning.py
> +    all_X, all_y = make_moons(noise=0.5, random_state=42)
Multi-grained scanning example should include sequential or image data processing.

2022-10-25 18:30 UTC, AndreyAgeev commented on bosk/block/zoo/multi_grained_scanning/multi_grained_scanning.py
> +        self._models: List[Tuple[Any, Any]] = [(RandomForestClassifier(random_state), ExtraTreesClassifier(random_state))
Fixed

2022-10-25 18:30 UTC, AndreyAgeev commented on bosk/block/zoo/multi_grained_scanning/multi_grained_scanning.py
> +        self._windows: List[int] = windows
fixed

2022-10-25 18:30 UTC, AndreyAgeev commented on bosk/block/zoo/multi_grained_scanning/multi_grained_scanning.py
> +    def _window_slicing_img(self, X, y, window, shape, stride=1):
fixed

2022-10-25 18:31 UTC, AndreyAgeev commented on bosk/block/zoo/multi_grained_scanning/multi_grained_scanning.py
> +        prf.fit(sliced_X, sliced_y)
Added enum for model type indexes

2022-10-25 18:31 UTC, AndreyAgeev commented on examples/deep_forests/mg_scanning/mg_scanning.py
> +    all_X, all_y = make_moons(noise=0.5, random_state=42)
Fixed

2022-10-26 10:24 UTC, andruekonst approved these changes

2022-10-26 10:24 UTC, merged