[BOSK-62] feat: XGBoost "CPUData"
NTAILab/bosk pull request #34
Opened 2023-03-19 10:42 UTC by AndreyAgeev

Added "CPUData" to main deep forest use cases, added example XGBoost for "GPUData" and "CPUData"

2023-03-19 10:47 UTC, AndreyAgeev commented on bosk/block/auto.py
> +        if len(fit_argnames) == 0:  # TODO: Arguments not found for XGBOOST
can't find arguments for methods XGBoost

2023-03-27 14:52 UTC, andruekonst requested changes

2023-03-27 14:52 UTC, andruekonst commented on examples/deep_forests/gpu/gpu_boosting.py
> +    rf_2 = b.XGBClassifier(tree_method="gpu_hist", random_state=42)(X=concat_1, y=y)
There is a doubt about XGBClassifier: can it work with JAX gpu data?

Probably, it just applies some trick like `np.asarray(X)`, i.e. downloads the data from GPU to CPU, then returns it back to GPU for ensemble construction, and finally converts data to NumPy CPU array.
So ain't it better not to move data to GPU using `MoveTo("GPU")` and run XGBoost directly on CPU data?

2023-03-27 16:05 UTC, AndreyAgeev commented on examples/deep_forests/gpu/gpu_boosting.py
> +    rf_2 = b.XGBClassifier(tree_method="gpu_hist", random_state=42)(X=concat_1, y=y)
Removed extra blocks`MoveTo("GPU")`

2023-03-27 16:06 UTC, AndreyAgeev commented on bosk/block/auto.py
> +        if len(fit_argnames) == 0:  # TODO: Arguments not found for XGBOOST
Fixed this moment

2023-03-27 16:41 UTC, andruekonst approved these changes

2023-03-27 16:41 UTC, merged